SELECT TRUNC(234.567, 1), TRUNC(234.567),
TRUNC(234.567,- 1), TRUNC(234.567, -2)
FROM DUAL;

SELECT SYSDATE, TRUNC(SYSDATE, 'MONTH')
FROM DUAL;

SELECT INITCAP('DATA BASE PROGRAM') FROM DUAL;

SELECT ENAME, INITCAP(ENAME)
FROM EMP
WHERE DEPTNO = 10;

SELECT 'Oracle'||' '||'DataBase' FROM DUAL;

SELECT CONCAT(CONCAT('Oracle',' '), 'DataBase') FROM DUAL;

SELECT LENGTH('DATA'), LENGTHB('DATA'), 
LENGTH('오라클'), LENGTHB('오라클') 
FROM DUAL;

SELECT DEPTNO, EMPNO, ENAME, LENGTH(ENAME)
FROM EMP
WHERE DEPTNO = 10;

SELECT * 
FROM EMP
WHERE LENGTH(ENAME) <= 4;

SELECT SUBSTR('DataBase', 2, 3), SUBSTR('DataBase', -4, 3)
FROM DUAL;

SELECT ENAME, SUBSTR(HIREDATE, 1, 2) FROM EMP
WHERE DEPTNO = 20;

SELECT ENAME, HIREDATE FROM EMP
WHERE SUBSTR(HIREDATE, 1, 2) = '82';

INSERT INTO EMP (EMPNO, ENAME, JOB, DEPTNO, HIREDATE)
VALUES (8888, 'TEST', 'TEST', 10, '1920/01/01');

INSERT INTO EMP (EMPNO, ENAME, JOB, DEPTNO, HIREDATE)
VALUES (9999, 'TEST1', 'TEST1', 10, '2020/01/01');

COMMIT;

SELECT * 
FROM EMP 
WHERE SUBSTR(HIREDATE, 1, 2) = '20';

SELECT *
FROM EMP
WHERE SUBSTR(ENAME, -1, 1) = 'N'; --WHERE ENAME LIKE '%N';

SELECT INSTR('DataBase', 'B') FROM DUAL;

SELECT DEPTNO, ENAME, INSTR(ENAME, 'E')
FROM EMP
WHERE DEPTNO = 30;

SELECT INSTR('DataBase', 'a', -5, 1), INSTR('DataBase', 'a', 3, 2)
FROM DUAL;

SELECT '20240115' || LPAD('12', 3, '0')
FROM DUAL;

SELECT LTRIM('aaaaDataBase Programingaaaa', 'a'), 
RTRIM('aaaaDataBase Programingaaaa', 'a'), 
TRIM('a' FROM 'aaaaDataBaseaaa Programingaaaa') 
FROM DUAL;

SELECT SYSDATE FROM DUAL;

SELECT SYSDATE, TO_CHAR(SYSDATE, 'YYYY-MM-DD HH12:MI:SS AM DAY') 
FROM DUAL;

SELECT TO_CHAR(SYSDATE, 'AM', 'NLS_DATE_LANGUAGE=AMERICAN') AS AMERICAN, 
TO_CHAR(SYSDATE, 'AM', 'nls_date_language=korean') AS KOREAN 
FROM DUAL;

SELECT TO_CHAR(SYSDATE, 'DAY', 'NLS_DATE_LANGUAGE=AMERICAN') AS AMERICAN, 
TO_CHAR(SYSDATE, 'DAY', 'nls_date_language=korean') AS KOREAN 
FROM DUAL;

SELECT * FROM EMP
WHERE SUBSTR(TO_CHAR(HIREDATE, 'YYYY'), 1, 4) = '1981';

SELECT EMPNO, TO_CHAR(HIREDATE, 'YYYY/MM/DD DAY') AS "STARTDAY"
FROM EMP
ORDER BY HIREDATE;

SELECT TO_CHAR(123456, '000,000,000') AS "000", 
TO_CHAR(123456, '999,999,999') AS "999"
FROM DUAL;

SELECT ENAME, SAL,
TO_CHAR(SAL, 'L999,999'), TO_CHAR(SAL, '$999,999')
FROM EMP
WHERE DEPTNO = 10;

SELECT TO_CHAR(0.1230) AS NUM1 ,
TO_CHAR(0.1230, 'FM999.9999') AS NUM2 ,
TO_CHAR(0.1230, 'FM999.0000') AS NUM3 ,
TO_CHAR(0.1230, 'FM000.000') AS NUM4 ,
TO_CHAR(0.1230, 'FM000.0000') AS NUM5
FROM DUAL;

SELECT TO_DATE (SYSDATE, 'YYYY-MM-DD')
--, TO_DATE (SYSTIMESTAMP, 'YYYY/MM/DD')
FROM DUAL;

SELECT SYSDATE, SYSTIMESTAMP FROM DUAL;

--SYSDATE는 문자자료형, 날짜자료형 다 있음
SELECT TO_DATE(SYSDATE, 'YYYY-MM-DD HH24:MI:SS'), SYSTIMESTAMP FROM DUAL;
SELECT TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS'), SYSTIMESTAMP FROM DUAL;

SELECT TO_DATE(SYSDATE, 'YYYY-MM-DD HH24:MI:SS')
, TO_CHAR(SYSTIMESTAMP, 'YYYY-MM-DD HH24:MI:SS.FF3') 
FROM DUAL;

SELECT NEXT_DAY(SYSDATE, '금') FROM DUAL;

SELECT NEXT_DAY(SYSDATE, '토요일'), NEXT_DAY(SYSDATE, 7) FROM DUAL; 

SELECT SYSDATE - 8, NEXT_DAY(SYSDATE - 8, '토요일') FROM DUAL;
SELECT LAST_DAY(SYSDATE) FROM DUAL; --현재 달 마지막날

SELECT 
FLOOR(MONTHS_BETWEEN(SYSDATE, TO_DATE('2011/01/01', 'YYYY/MM/DD'))/12)||'년차'
AS "연차"
FROM DUAL;

SELECT TO_NUMBER('10,000', '999,999'), 
TO_NUMBER('20,000', '999,999'), 
TO_NUMBER('10,000', '999,999') + TO_NUMBER('20,000', '999,999')
AS SUM FROM DUAL;

SELECT ENAME, SAL, COMM, NVL(COMM, 0), JOB FROM EMP;

SELECT 
ROUND(AVG(NVL(COMM, 0)), 3) AS AVG1, --NULL은 0으로 바꾸고 평균(14)
AVG(COMM) AS AVG2 --NULL은 제외하고 평균(4)
FROM EMP; 

SELECT ENAME, SAL, COMM, NVL(SAL, 0)*12+NVL(COMM, 0) 
FROM EMP; --NULL은 연산 자체가 안됨

SELECT ENAME, COMM, MGR, SAL, NVL2(COMM, MGR, SAL) FROM EMP;

SELECT COMM, NVL2(COMM, 0, 100)
FROM EMP;

--커미션을 받지 못한 사람의 인원수는
SELECT COUNT(*)
FROM EMP
WHERE NVL(COMM, 0) = 0;

SELECT POWER(5, 2), ROUND(SQRT(2), 4), SQRT(9) FROM DUAL;

SELECT ENAME, DEPTNO, 
DECODE(DEPTNO, 
10, 'ACCOUNTING',
20, 'RESEARCH',
'ETC'
) AS DNAME FROM EMP;

SELECT ENAME, JOB, SAL, 
DECODE (JOB, 
'ANALYST', SAL * 1.05,
'SALESMAN', SAL * 1.1,
'MANAGER', SAL * 1.15,
'CLERK', SAL * 1.2,
NVL(SAL,0)
) AS 급여인상
FROM EMP
ORDER BY JOB;