SELECT ENAME, DEPTNO, 
CASE WHEN DEPTNO = 10 THEN 'ACCOUNTING' 
WHEN DEPTNO = 20 THEN 'RESEARCH'
ELSE 'OPERATIONS'
--CASE DEPTNO
--WHEN 10 THEN 'ACCOUNTING' 
--WHEN 20 THEN 'RESEARCH'
--ELSE 'OPERATIONS'
END AS DNAME
FROM EMP;

SELECT ENAME, JOB, SAL, 
CASE JOB 
WHEN 'ANALYST' THEN (SAL + SAL * 0.05)
WHEN 'SALESMAN' THEN (SAL + SAL * 0.1)
WHEN 'MANAGER' THEN (SAL + SAL * 0.15)
WHEN 'CLERK' THEN (SAL + SAL * 0.2)
END 급여인상
FROM EMP;

SELECT ENAME, SAL, 
CASE
WHEN SAL >= 5000 THEN 'KING'
WHEN SAL >= 3000 THEN 'HIGH'
WHEN SAL >= 1500 THEN 'MIDDLE'
ELSE 'LOW'
END 비고
FROM EMP;

--사원번호, 사원명, 연봉 3개의 컬럼으로 구성된 EMP01 테이블 생성
CREATE TABLE EMP01(
EMPNO NUMBER(4), --(4)에는 ,0이 생략 됨 = (4, 0)
ENAME VARCHAR2(20),
SAL NUMBER(7, 2)
);
SELECT * FROM TAB;
DESC EMP01;

CREATE TABLE DEPT01 (
DEPTNO NUMBER(2),
DNAME VARCHAR2(14),
LOC VARCHAR2(13)
);
SELECT * FROM TAB;
DESC EMP01;

ALTER TABLE EMP01
ADD JOB VARCHAR2(9);

ALTER TABLE DEPT01
ADD CREDATE DATE;

ALTER TABLE EMP01
DROP (SAL, JOB);

ALTER TABLE EMP01
ADD (JOB VARCHAR2(9), 
MGR NUMBER(4), 
HIREDATE DATE, 
SAL NUMBER(7,2), 
COMM NUMBER(7,2), 
DEPTNO NUMBER(2)
);
DESC EMP01;

INSERT ALL
INTO EMP01
VALUES (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
SELECT * FROM EMP;
COMMIT;

ALTER TABLE EMP01
ADD TEST VARCHAR2(9);

ALTER TABLE EMP01
MODIFY TEST NUMBER(4);
DESC EMP01;

--EMP01테이블에서 9999사번인 사원의 TEST컬럼의 값을 2525로 변경하세요
UPDATE EMP01
SET TEST = 2525
WHERE EMPNO = 9999;
COMMIT;

--EMP01테이블에서 TEST컬럼의 자료형을 VARCHAR2(20)으로 변경하세요
ALTER TABLE EMP01
MODIFY TEST VARCHAR2(20); --위에서 값을 변경해서 자료형 변경 불가능

--EMP01테이블에서 9999사번인 사원의 TEST컬럼의 값을 NULL로 변경하세요
UPDATE EMP01
SET TEST = NULL -- = ''
WHERE EMPNO = 9999;
COMMIT;

--EMP01테이블에서 TEST컬럼의 자료형을 VARCHAR2(20)으로 변경하세요
ALTER TABLE EMP01
MODIFY TEST VARCHAR2(20);

--EMP01테이블에서 사번이 9999인 사원의 TSET컬럼 값을 '학생'으로 변경하세요
UPDATE EMP01
SET TEST = '교환학생'
WHERE EMPNO = 9999;
COMMIT;

--EMP01테이블에서 TEST컬럼을 VARCHAR2(12)으로 변경하세요
ALTER TABLE EMP01
MODIFY TEST VARCHAR2(12);

UPDATE EMP01
SET TEST = NULL;
COMMIT;

--EMP01테이블에서 TEST컬럼을 NUMBER(6)으로 변경하세요
ALTER TABLE EMP01
MODIFY TEST NUMBER(6);
DESC EMP01;

--EMP01테이블에서 9999사번의 TEST컬럼에 값을 25로 변경
UPDATE EMP01
SET TEST = 25
WHERE EMPNO = 9999;
COMMIT;

--EMP01테이블에서 TEST컬럼을 NUMBER(2)으로 변경하세요
ALTER TABLE EMP01
MODIFY TEST NUMBER(7);

--EMP01테이블에서 TEST컬럼을 TEST1로 이름을 변경
ALTER TABLE EMP01
RENAME COLUMN TEST TO TEST1;
DESC EMP01;

--EMP01테이블에서 TEST1컬럼을 삭제
ALTER TABLE EMP01
DROP COLUMN TEST1;
DESC EMP01;

--EMP01테이블의 이름을 EMP02로 변경
RENAME EMP01 TO EMP02;
SELECT * FROM TAB;

--EMP02테이블의 데이터를 모두 제거하세요
TRUNCATE TABLE EMP02;
ROLLBACK;

--EMP02, DEPT01 테이블을 모두 제거하세요. 휴지통에 가지않고 영구삭제
DROP TABLE DEPT01 PURGE;

--우리반 학생정보를 테이블로 생설할 예정
-- 번호, 이름, 성별
-- 테이블명 : ONECLASS 
CREATE TABLE ONECLASS (NUM NUMBER(2), NAME VARCHAR2(20), GENDER VARCHAR2(6));
INSERT INTO ONECLASS VALUES (1, '제동현', '남');
INSERT INTO ONECLASS VALUES (2, '임정혁', '남');
INSERT INTO ONECLASS VALUES (3, '김동욱', '남');
INSERT INTO ONECLASS VALUES (4, '김동준', '남');
INSERT INTO ONECLASS VALUES (5, '방이삭', '남');
INSERT INTO ONECLASS VALUES (6, '정하경', '남');
INSERT INTO ONECLASS VALUES (7, '금아롬', '여');
INSERT INTO ONECLASS VALUES (8, '양예진', '여');
INSERT INTO ONECLASS VALUES (9, '홍수민', '여');
INSERT INTO ONECLASS VALUES (10, '이환석', '남');
INSERT INTO ONECLASS VALUES (11, '김성태', '남');
INSERT INTO ONECLASS VALUES (12, '이영은', '여');
INSERT INTO ONECLASS VALUES (13, '정하영', '여');
INSERT INTO ONECLASS VALUES (14, '김준성', '남');
INSERT INTO ONECLASS VALUES (15, '변유림', '여');
INSERT INTO ONECLASS VALUES (16, '김성준', '남');
INSERT INTO ONECLASS VALUES (17, '성한규', '남');
INSERT INTO ONECLASS VALUES (18, '김호석', '남');
INSERT INTO ONECLASS VALUES (19, '박재영', '남');
INSERT INTO ONECLASS VALUES (20, '남태욱', '남');
INSERT INTO ONECLASS VALUES (21, '조이상', '남');
INSERT INTO ONECLASS VALUES (22, '이상민', '남');
COMMIT;

ALTER TABLE ONECLASS
RENAME COLUMN NUM TO NO;

UPDATE ONECLASS
SET GENDER = '남자'
WHERE GENDER = '남';
COMMIT;

SELECT * FROM ONECLASS;

ALTER TABLE ONECLASS
ADD DIV NUMBER(1);

DESC ONECLASS;

--1.  ONECLASS 테이블에 분단(DIV)에 해당하는 컬럼을 추가하세요
--(값은  1 또는 2로 들어갈 예정)
ALTER TABLE ONECLASS
ADD DIV NUMBER(1);

--2.  학생 정보에 맞는 분단수에 대한 정보를 넣으세요.
UPDATE ONECLASS
SET DIV = 1
WHERE NO IN (1, 7, 12, 13, 14, 15, 17, 19, 20, 21);

UPDATE ONECLASS
SET DIV = 2
WHERE DIV IS NULL;
COMMIT;

SELECT * FROM ONECLASS;

--3. 아래의 학생 정보가 해당 번호로 오도록 수정하세요.
--(14번의 번호값이 동일한 값이 존재하면 안됨)
--번호 : 14
--이름 : 윤서해
--성별 : 여자
--분단 : 2
UPDATE ONECLASS
SET NO = NO + 1
WHERE NO >= 14;

INSERT INTO ONECLASS VALUES (14, '윤서해', '여자', 2);
COMMIT;

SELECT * FROM ONECLASS ORDER BY NO;

--4. ONECLASS 테이블에서 분단이 몇 분단이 있는지 종류를 중복값 없이 출력하세요.
SELECT DIV FROM ONECLASS GROUP BY DIV;
SELECT DISTINCT DIV FROM ONECLASS;

--5. ONECLASS 테이블에서 어떠한 성별이 있는지 중복값 없이 출력하세요.
SELECT GENDER FROM ONECLASS GROUP BY GENDER;
SELECT DISTINCT GENDER FROM ONECLASS;

--6. 분단별 남자, 여자의 인원수를 출력하세요.
SELECT DIV || '분단', GENDER, COUNT(*) || '명'
FROM ONECLASS
GROUP BY DIV, GENDER
ORDER BY DIV;

--7. 해당 학생의 정보를 넣으세요.
--번호 : 24
--이름 : 홍유령
--성별 : 자신들이 정하세요
--분단 : 2
INSERT INTO ONECLASS VALUES (24, '홍유령', '여자', 2);
COMMIT;

--8. 이름이 "김"가로 시작하는 학생의 번호, 이름을 가져오세요.
SELECT NO, NAME FROM ONECLASS WHERE NAME LIKE '김%';
SELECT NO, NAME FROM ONECLASS WHERE SUBSTR(NAME, 1, 1) = '김';

--9. ONE클래스의 인원수가 몇 명인지 검색하세요.
SELECT COUNT(*)||'명' FROM ONECLASS;
SELECT MAX(NO)||'명' FROM ONECLASS;

--10. ONE클래스에서 여자의 인원수만 몇명인지 검색하세요.
SELECT GENDER, COUNT(*) 
FROM ONECLASS 
GROUP BY GENDER 
HAVING GENDER = '여자';

SELECT GENDER, COUNT(*)
FROM ONECLASS
WHERE GENDER = '여자'
GROUP BY GENDER;

--11. ONE클래스테이블에 전화번호(PHONE)컬럼을 NUMBER자료형으로 추가하세요.
ALTER TABLE ONECLASS ADD PHONE NUMBER(11);

--11 컬럼에 값넣기
UPDATE ONECLASS
SET PHONE = 01050645726
WHERE NAME = '김동준';
COMMIT;

--11 번호를 010-0000-0000으로 바꾸기
SELECT NO, NAME, 
'0'||SUBSTR(PHONE,1,2)||'-'||SUBSTR(PHONE,3,4)||'-'||SUBSTR(PHONE,7,4)
FROM ONECLASS
WHERE NAME = '김동준';

SELECT NO, NAME, NVL2(PHONE, '010-5064-5726', 0)
FROM ONECLASS
WHERE NAME = '김동준';

SELECT NO, NAME, 
REPLACE(TO_CHAR(PHONE, '000,0000,0000'), ',', '-') PHONE
FROM ONECLASS WHERE NAME = '김동준';

--12. ONE클래스테이블의 전화번호 컬럼의 이름을 TEL로 변경하세요.
ALTER TABLE ONECLASS
RENAME COLUMN PHONE TO TEL;

--13. ONE클래스테이블의 전화번호 컬럼의 자료형을 VARCHAR2자료형으로 변경하세요.
UPDATE ONECLASS
SET TEL = NULL;
COMMIT;
ALTER TABLE ONECLASS
MODIFY TEL VARCHAR2(13);

--14. ONE클래스 테이블에서 여자만 삭제하세요.
DELETE FROM ONECLASS WHERE GENDER = '여자';
COMMIT;

--15. ONE클래스 테이블에서 번호를 순서에 맞게 변경하세요.
UPDATE ONECLASS
SET NO = 16
WHERE NAME = '박재영';
COMMIT;

--16. ONE클래스 테이블의 데이터를 모두 제거하세요.
TRUNCATE TABLE ONECLASS;

DELETE FROM ONECLASS; 
COMMIT;

--17. ONE클래스 테이블의 TEL컬럼을 삭제하세요.
ALTER TABLE ONECLASS
DROP COLUMN TEL;
--DROP (TEL);

--18. ONE클래스 테이블을 제거하세요.
DROP TABLE ONECLASS PURGE;

--두번째 글자부터 대문자로(함수활용)
SELECT LOWER(SUBSTR(ENAME, 1,1))||INITCAP(SUBSTR(ENAME, 2,LENGTH(ENAME))) 
FROM EMP;