--1. 사원의 급여에 12를 곱한 결과만 출력되도록 수식을 적용하고, 수식의 별칭을 "연봉" 으로 표시하시오.
SELECT (SALARY * 12) 연봉
FROM EMPLOY;


--2. 업무가 '세일즈' 인 사원의 이름, 업무, 부서아이디를 검색하시오.
SELECT NAME, JOB, DEPTID
FROM EMPLOY
WHERE JOB = '세일즈';


--3. 입사일이 '2001년 12월 3일' 인 사원을 검색하시오.
SELECT *
FROM EMPLOY
WHERE HIREDATE = '01/12/03';


--4. 급여가 3000 이상이고 5000 이하인 사원의 이름, 급여를 검색하시오.
SELECT NAME, SALARY
FROM EMPLOY
WHERE SALARY >= 3000 AND SALARY <= 5000;
SELECT NAME, SALARY FROM EMPLOY WHERE SALARY BETWEEN 3000 AND 5000;


--5. 업무가 '사무직' 이거나 '경리' 인 사원을 검색하시오.
SELECT *
FROM EMPLOY
WHERE JOB = '사무직' OR JOB = '경리';
SELECT * FROM EMPLOY WHERE JOB IN ('사무직', '경리');


--6. 급여가 3000 이상이고 업무가 '부장' 인 사원을 검색하시오.
SELECT *
FROM EMPLOY
WHERE SALARY >= 3000 AND JOB = '부장';


--7. 업무가  '세일즈' 가 아니거나 '사무직'이 아닌 사원을 검색하시오.
SELECT *
FROM EMPLOY
WHERE JOB != '세일즈' AND JOB != '사무직';
SELECT * FROM EMPLOY WHERE JOB NOT IN ('세일즈', '사무직');


--8. 이름에 '철' 이라는 문자를 포함하는 경우의 사원을 검색하시오.
SELECT *
FROM EMPLOY
WHERE NAME LIKE '%철%';


--9. 보너스를 받지 않는 사원을 검색하시오.
SELECT *
FROM EMPLOY
WHERE NVL(BONUS, 0) = 0;
SELECT * FROM EMPLOY WHERE BONUS = 0 OR BONUS IS NULL;


--10. 2001년 이후에 입사한 사원을 삭제하시오.
DELETE FROM EMPLOY
WHERE HIREDATE >= '2001/01/01';
DELETE FROM EMPLOY WHERE TO_CHAR(HIREDATE, 'YYYY') >= '2001';

COMMIT;
ROLLBACK;

CREATE TABLE EMP01 (
EMPNO NUMBER(4),
ENAME VARCHAR2(10),
JOB VARCHAR2(9),
DEPTNO NUMBER(4)
);

INSERT INTO EMP01
VALUES (NULL, '', 'SALESMAN', 30);

INSERT INTO EMP01
VALUES (NULL, 'TOM', 'SALESMAN', 30);

INSERT INTO EMP01
VALUES (NULL, 'TOM', 'RESEARCH', 20);

SELECT * FROM EMP01;
COMMIT;
SELECT * FROM EMP01 WHERE ENAME IS NULL;

CREATE TABLE EMP02(
EMPNO NUMBER(4) NOT NULL,
ENAME VARCHAR2(10) NOT NULL,
JOB VARCHAR2(9),
DEPTNO NUMBER(4)
);

INSERT INTO EMP02
VALUES (1000, NULL, 'SALESMAN', 10);
--오류

INSERT INTO EMP02
VALUES (1401, 'TOM', '', 10);

SELECT * FROM EMP02;

CREATE TABLE EMP03(
EMPID VARCHAR2(20) UNIQUE NOT NULL,
EMPNO NUMBER(4) UNIQUE,
ENAME VARCHAR2(10) NOT NULL,
JOB VARCHAR2(9),
DEPTNO NUMBER(4)
);

INSERT INTO EMP03
VALUES ('emp03', 7499, 'ALLEN', 'SALESMAN', 30);

--INSERT INTO EMP03
--VALUES ('emp02', 7499, 'JONES', 'MANAGER', 20);
--오류

--INSERT INTO EMP03
--VALUES (NULL, NULL, 'JONES', 'SALESMAN', 10);
--오류

INSERT INTO EMP06
VALUES ('emp05', NULL, 'JONES', 'SALESMAN', 10);

SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME
FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'EMP02';

SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'EMP02';

DESC USER_CONSTRAINTS;

CREATE TABLE EMP04(
EMPNO NUMBER(4) PRIMARY KEY, --반드시 한 테이블안에 PRIMARY KEY 조건은 한 개만 존재해야 함
ENAME VARCHAR2(10) NOT NULL,
JOB VARCHAR2(9),
DEPTNO NUMBER(4)
);

INSERT INTO EMP04 VALUES (7499, 'ALLEN', 'SALESMAN', 30);
--INSERT INTO EMP04 VALUES (7499, 'JONES', 'MANAGER', 20);
--오류
--INSERT INTO EMP04 VALUES (NULL, 'JONES', 'MANAGER', 20);
--오류

SELECT * FROM EMP04;

SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME
FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'EMP04';

SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME
FROM USER_CONSTRAINTS;


CREATE TABLE DEPT01 (
DEPTNO NUMBER(2) CONSTRAINT DEPT01_DEPTNO_PK PRIMARY KEY,
DNAME VARCHAR2(15),
LOC VARCHAR2(15)
);

INSERT INTO DEPT01
VALUES (50, 'RESEARCH', '뉴욕');

INSERT INTO DEPT01 (DEPTNO, DNAME, LOC)
VALUES (60, 'RESEARCH', '뉴욕');

--INSERT INTO DEPT01 (DEPTNO, DNAME, LOC)
--VALUES (50, 'TEACHER', '서울');
--오류

SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME
FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'DEPT01';

CREATE TABLE DEPT02 (
DEPTNO NUMBER(2),
DNAME VARCHAR2(15),
LOC VARCHAR2(15),
CONSTRAINT DEPT02_DNO_DNAM_PK PRIMARY KEY(DEPTNO, DNAME)
);

INSERT INTO DEPT02 VALUES (15, '영업', '서울');
INSERT INTO DEPT02 VALUES (15, '개발', '서울');
--INSERT INTO DEPT02 VALUES (15, '개발', '인천'); --에러
--INSERT INTO DEPT02 VALUES (15, NULL, '인천'); --에러

SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME
FROM USER_CONSTRAINTS;

CREATE TABLE DEPT03 (
DEPTNO NUMBER(2),
DNAME VARCHAR2(15),
LOC VARCHAR2(15)
);

ALTER TABLE DEPT03
ADD CONSTRAINT DEPT03_DEPTNO_PK PRIMARY KEY (DEPTNO);

ALTER TABLE DEPT03
MODIFY DNAME UNIQUE NOT NULL;

SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME
FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'DEPT03';

ALTER TABLE DEPT03
DROP CONSTRAINT SYS_C007040;

ALTER TABLE DEPT03
MODIFY DEPTNO CONSTRAINT DEPT03_DEPTNO_PK PRIMARY KEY;

ALTER TABLE DEPT03
MODIFY DNAME CONSTRAINT DEPT03_DNAME_NN NOT NULL;


CREATE TABLE DEPT03 (
DEPTNO NUMBER(2),
DNAME VARCHAR2(15),
LOC VARCHAR2(15)
);

ALTER TABLE DEPT03 ADD CONSTRAINT DEPT03_DEPTNO_PK PRIMARY KEY (DEPTNO);

ALTER TABLE DEPT03 MODIFY DNAME UNIQUE NOT NULL;

ALTER TABLE DEPT03 DROP CONSTRAINT SYS_C007040;

ALTER TABLE DEPT03 MODIFY DEPTNO CONSTRAINT DEPT03_DEPTNO_PK PRIMARY KEY;

ALTER TABLE DEPT03 MODIFY DNAME CONSTRAINT DEPT03_DNAME_NN NOT NULL;


CREATE TABLE EMP05 (
EMPNO NUMBER(4) PRIMARY KEY,
ENAME VARCHAR2(10) NOT NULL,
GENDER VARCHAR2(1) CHECK (GENDER IN ('M', 'F'))
);

INSERT INTO EMP05 VALUES (7566, 'JONES', 'M');
INSERT INTO EMP05 VALUES (7577, 'LEMON', 'F');
--INSERT INTO EMP05 VALUES (7588, 'TOMS', 'A'); --오류
--INSERT INTO EMP05 VALUES (7566, 'JONES', 'm'); --오류

--ALTER TABLE EMP05 MODIFY EMPNO CHECK (EMPNO BETWEEN 1000 AND 9999);
--ALTER TABLE EMP05 DROP CONSTRAINT SYS_C007046;


CREATE TABLE EMP07 (
EMPNO NUMBER(4) PRIMARY KEY,
ENAME VARCHAR2(10) NOT NULL,
GENDER VARCHAR2(1) CHECK (GENDER IN ('M', 'F')),
SAL NUMBER(7,2) CHECK(SAL >= 1000 AND SAL <= 10000)
);

INSERT INTO EMP07 VALUES ('TOMS', 'TOMS', 'M', 1500);
--INSERT INTO EMP07 VALUES (1234, 'TOMS', 'M', 15000); --오류

SELECT * FROM USER_CONSTRAINTS;
SELECT * FROM USER_CONS_COLUMNS;

TRUNCATE TABLE DEPT01;

INSERT ALL INTO DEPT01 VALUES (DEPTNO, DNAME, LOC) SELECT * FROM DEPT;

SELECT * FROM DEPT01;

CREATE TABLE EMP06 (
EMPNO NUMBER(4) PRIMARY KEY,
ENAME VARCHAR2(10) NOT NULL,
JOB VARCHAR2(9),
DEPTNO NUMBER(4) REFERENCES DEPT01(DEPTNO) --참조 무결성 => 10, 20, 30, 40, NULL
);
SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'EMP06';

INSERT INTO EMP06 VALUES (7566, 'JONES', 'MANAGER', 40);
INSERT INTO EMP06 VALUES (7988, 'JERRY', 'CEO', NULL);
INSERT INTO EMP06 VALUES (7989, 'JERRY', 'CEO', 40);
--INSERT INTO EMP06 VALUES (7889, 'JERRY', 'CEO', 50); --오류

DROP TABLE EMP07 PURGE;

CREATE TABLE EMP07 (
EMPNO NUMBER(4) PRIMARY KEY,
ENAME VARCHAR2(10) NOT NULL,
JOB VARCHAR2(9),
DEPTNO NUMBER(4),
CONSTRAINT EMP07_DEPTNO_FK FOREIGN KEY(DEPTNO) REFERENCES DEPT02(DEPTNO)
);

CREATE TABLE EMP07 (
EMPNO NUMBER(4) PRIMARY KEY,
ENAME VARCHAR2(10) NOT NULL,
JOB VARCHAR2(9),
DEPTNO NUMBER(4),
DNAME VARCHAR2(10),
CONSTRAINT EMP07_DEPTNO_FK FOREIGN KEY(DEPTNO, DNAME) REFERENCES DEPT02(DEPTNO, DNAME),
CONSTRAINT EMP07_DEPTNO_FK FOREIGN KEY(DEPTNO) REFERENCES DEPT02(DEPTNO)
);



DROP TABLE EMP07 PURGE;

CREATE TABLE EMP07 (
EMPNO NUMBER(4) PRIMARY KEY,
ENAME VARCHAR2(10) NOT NULL,
JOB VARCHAR2(9),
DEPTNO NUMBER(4),
CONSTRAINT EMP07_DEPTNO_FK FOREIGN KEY(DEPTNO) REFERENCES DEPT02(DEPTNO)
);

CREATE TABLE EMP07 (
EMPNO NUMBER(4) PRIMARY KEY,
ENAME VARCHAR2(10) NOT NULL,
JOB VARCHAR2(9),
DEPTNO NUMBER(4),
DNAME VARCHAR2(10),
CONSTRAINT EMP07_DEPTNO_FK FOREIGN KEY(DEPTNO, DNAME) REFERENCES DEPT02(DEPTNO, DNAME),
CONSTRAINT EMP07_DEPTNO_FK FOREIGN KEY(DEPTNO) REFERENCES DEPT02(DEPTNO)
);