DELETE FROM MENU_INFO WHERE MENU_NO = 88;
rollback;

UPDATE MENU_INFO SET MENU_CAT = ?, MENU_NM = ?, MENU_PR = ?, MENU_WG = ?, MENU_ML = ?, 
MENU_K = ?, MENU_SU = ?, MENU_D = ?, MENU_F = ?, MENU_N = ?, MENU_C = ?, MENU_DC = ? 
WHERE MENU_NO = 87;

INSERT INTO ORDER_LIST(ORDER_NUM, ORDER_PN, ORDER_ADR, ORDER_REQ, ORDER_NM) 
VALUES (1, '01011112222', '경기도 안양시', NULL, '개구리');

INSERT INTO ORDER_LIST(ORDER_NUM, ORDER_PN, ORDER_ADR, ORDER_REQ, ORDER_NM) 
VALUES(TO_CHAR(SYSDATE,'YYYYMMDD')||TO_CHAR(SEQ_ORDER.NEXTVAL,'0000'), '01033332222', '경기도 안양시', NULL, '올챙이');

SET SERVEROUTPUT ON
BEGIN
DBMS_OUTPUT.PUT_LINE(TO_CHAR(SYSDATE,'YYYYMMDD')||TO_CHAR(SEQ_ORDER.NEXTVAL,'0000'));
END;
/

SELECT MENU_PR FROM MENU_INFO WHERE MENU_NO = 7;

INSERT INTO ORDER_LIST(ORDER_NUM, ORDER_PN, ORDER_ADR, ORDER_REQ, ORDER_NM) 
VALUES (1, '01011112222', '경기도 안양시', NULL, '개구리');

INSERT INTO ORDER_LIST(ORDER_NUM, ORDER_PN, ORDER_ADR, ORDER_REQ, ORDER_NM, ORDER_NICK, ORDER_MENUNO, ORDER_EA, ORDER_TOT)
VALUES(TO_CHAR(SYSDATE,'YYYYMMDD')||TO_CHAR(SEQ_ORDER.NEXTVAL,'0000'), '01033337777', 
'광명시', '', '동준', '개굴', 3, 5, (SELECT MENU_PR * 5 FROM MENU_INFO WHERE MENU_NO = 3));

SELECT MENU_PR FROM MENU_INFO WHERE MENU_NO = 3;

--TRIM (' ' FROM ORDER_NUM)
SELECT TRIM (' ' FROM ORDER_NUM) FROM ORDER_LIST WHERE ORDER_ADR = '광명시';

--UPDATE ORDER_LIST SET ORDER_NUM = (SELECT ORDER_NUM FROM ORDER_LIST WHERE ORDER_NM = '"+order_nm+"') "
--									+ "WHERE ORDER_NM = '" + order_nm + "
SELECT MIN(ORDER_NUM) FROM ORDER_LIST WHERE ORDER_NM = '김동준' AND ORDER_ADR = '경기도 광명시';

--상품번호 : [1, 2, 3, 1, 40, 60], 상품수량 : [2, 3, 4, 3, 2, 2]
SELECT  MENU_PR * 2 FROM MENU_INFO WHERE MENU_NO = ?;


SELECT DISTINCT ORDER_BR, ORDER_DT, ORDER_MA FROM ORDER_LIST WHERE ORDER_NM = '김동준';
SELECT DISTINCT ORDER_NM, ORDER_PN, ORDER_ADR FROM ORDER_LIST WHERE ORDER_NM = '김동준';

SELECT sum(ORDER_TOT) TOTAL FROM ORDER_LIST GROUP BY ORDER_NUM;

--ORDER_BR //지정명
--ORDER_DT //주문일자
--ORDER_MA //담당자명
--ORDER_NM //주문자
--ORDER_PN //연락처
--ORDER_ADR //주소
--
--주문내용 (메뉴이름 수량 총액)
--ORDER_MENUNO ORDER_EA ORDER_TOT
-- 싸그리총액
--ORDER_REQ //요청사항
--o.ORDER_NM, o.ORDER_PN, o.ORDER_ADR, 
SELECT m.MENU_NM, o.ORDER_EA, o.ORDER_TOT
FROM ORDER_LIST o, menu_info m 
WHERE m.MENU_NO = o.ORDER_MENUNO and o.ORDER_NM = '김동준';

SELECT m.MENU_NM, o.ORDER_EA, o.ORDER_TOT
FROM ORDER_LIST o, menu_info m 
WHERE m.MENU_NO = o.ORDER_MENUNO and o.ORDER_NM = '김동준'
GROUP BY m.MENU_NM, o.ORDER_EA, o.ORDER_TOT;

select MENU_NM, sum(ORDER_EA), sum(ORDER_TOT)
from ORDER_LIST o, menu_info m
where MENU_NO = ORDER_MENUNO and ORDER_NM = '김동준'
GROUP BY MENU_NM
ORDER BY sum(ORDER_TOT) DESC;

UPDATE ORDER_LIST 
SET ORDER_NUM = TO_CHAR(SYSDATE,'YYYYMMDD')||TO_CHAR(SEQ_ORDER.NEXTVAL,'FM0000') 
WHERE ORDER_ADR = '경기도 군포시';

SELECT * FROM ORDER_LIST WHERE ORDER_NM = '제동현' and ORDER_MENUNO = 1 GROUP BY ORDER_NUM;

SELECT * FROM ORDER_LIST WHERE ORDER_ADR = '경기도 군포시';

(SELECT MAX(TO_NUMBER(ORDER_NUM)) FROM ORDER_LIST WHERE ORDER_NM = '홍길동' AND ORDER_ADR = '첝국');

UPDATE ORDER_LIST 
SET ORDER_NUM =  (SELECT MAX(TO_NUMBER(ORDER_NUM)) FROM ORDER_LIST WHERE ORDER_NM = '홍길동' AND ORDER_ADR = '첝국')
WHERE ORDER_NM = '홍길동';

SELECT * FROM ORDER_LIST where ORDER_NM = '남태욱';

SELECT SUM(ORDER_TOT) TOTAL FROM ORDER_LIST GROUP BY ORDER_NUM WHERE ORDER_NM = '홍길동' AND ORDER_ADR = '첝국';