CREATE TABLE MEM_INFO (
        USER_NM        VARCHAR2(12) NOT NULL,
        USER_NICK        VARCHAR2(30) PRIMARY KEY,
        USER_PN                NUMBER(11) NOT NULL,
        USER_ADDR        VARCHAR2(100) NOT NULL
);

CREATE TABLE MENU_INFO (
MENU_CAT        VARCHAR2(15) NOT NULL,
MENU_NO        NUMBER(4) PRIMARY KEY,
MENU_NM        VARCHAR2(100) NOT NULL UNIQUE,
MENU_PR        NUMBER(10) NOT NULL,
MENU_WG        NUMBER(4) ,
MENU_ML        NUMBER(4) ,
MENU_K        NUMBER(5,1) NOT NULL,
MENU_SU        NUMBER(5,1) NOT NULL,
MENU_D        NUMBER(5,1) NOT NULL,
MENU_F        NUMBER(5,1) NOT NULL,
MENU_N        NUMBER(5,1) NOT NULL,
MENU_C        NUMBER(5,1) NOT NULL,
MENU_DC        VARCHAR2(500) 
);			

CREATE TABLE ORDER_LIST (
ORDER_NUM        VARCHAR2(15), --주문번호
ORDER_PN        VARCHAR2(13) NOT NULL, --휴대폰 번호
ORDER_ADR        VARCHAR2(100) NOT NULL, --주소
ORDER_REQ        VARCHAR2(150), -- 요청사항
ORDER_NM        VARCHAR2(12), --주문자명
ORDER_NICK VARCHAR2(30) DEFAULT '(비회원)', --닉네임
ORDER_STATUS VARCHAR2(30), --주문상태
ORDER_MA        VARCHAR2(10) DEFAULT '김동준', --주문담당자
ORDER_BR        VARCHAR2(30) DEFAULT '맥도날드 안양점', -- 지점
ORDER_DT        DATE DEFAULT SYSDATE, -- 주문일자
ORDER_MENUNO NUMBER(4), --주문한 메뉴 넘버
ORDER_EA NUMBER(3), -- 주문한 메뉴 갯수
ORDER_TOT NUMBER(10) -- 주문한 메뉴 총액
);

DROP TABLE ORDER_LIST PURGE;

ROLLBACK;
COMMIT;

CREATE SEQUENCE SEQ_MENUNO NOCACHE;
CREATE SEQUENCE SEQ_ORDER NOCACHE;

DROP SEQUENCE SEQ_ORDER;