CREATE TABLE PAY (
MEMID VARCHAR2(12) PRIMARY KEY,
ORDERID VARCHAR2(12),
PRICE NUMBER);

CREATE TABLE ORDERLIST (
ORDERID VARCHAR2(12) PRIMARY KEY,
PRODUCTNAME VARCHAR2(20));

CREATE TABLE SCORE (
HAK VARCHAR2(10),
NAME VARCHAR2(20) NOT NULL,
KOR NUMBER(3), 
ENG NUMBER(3), 
MAT NUMBER(3),
CONSTRAINT PK_SCORE_HAK PRIMARY KEY(HAK));

CREATE TABLE BOARD (
ID NUMBER PRIMARY KEY,
WRITER VARCHAR2(12),
PASSWD VARCHAR2(12),
SUBJECT VARCHAR2(50),
EMAIL VARCHAR2(25));

CREATE SEQUENCE BOARD_SEQ;

INSERT INTO BOARD VALUES (BOARD_SEQ.NEXTVAL, '관리자', '1111', '공지합니다', 'admin@a.b');

COMMIT;