--회원정보 테이블
CREATE TABLE TB_MEMBER (
M_SEQ NUMBER CONSTRAINT PK_MEMBER_SEQ PRIMARY KEY,
M_USERID VARCHAR2(20) NOT NULL,
M_PWD VARCHAR2(20) NOT NULL,
M_EMAIL VARCHAR2(50),
M_HP VARCHAR2(20),
M_REGISTDATE DATE DEFAULT SYSDATE,
M_POINT NUMBER DEFAULT 0
);

CREATE SEQUENCE SEQ_TB_MEMBER;

INSERT INTO TB_MEMBER (M_SEQ, M_USERID, M_PWD, M_EMAIL, M_HP) 
VALUES (SEQ_TB_MEMBER.NEXTVAL, 'apple', '1111', 'apple@apple.com', '010-8888-9999');

COMMIT;

SELECT * FROM TB_MEMBER ORDER BY M_SEQ DESC;

ALTER TABLE TB_MEMBER ADD RDATE TIMESTAMP;

CREATE TABLE MEMBER (
ID VARCHAR2(12),
PASSWD VARCHAR2(12),
NAME VARCHAR2(12),
AGE NUMBER(3),
ADDR VARCHAR2(20),
EMAIL VARCHAR2(20)
);

INSERT INTO MEMBER VALUES ('aaa', 'aaa', '박재영', 32, '서울시', 'a@a.com');
INSERT INTO MEMBER VALUES ('bbb', 'bbb', '임정혁', 31, '인천시', 'b@b.com');
INSERT INTO MEMBER VALUES ('ccc', 'ccc', '조영미', 35, '강원도', 'c@c.com');
INSERT INTO MEMBER VALUES ('ddd', 'ddd', '홍수민', 33, '제주시', 'd@d.com');
INSERT INTO MEMBER VALUES ('eee', 'eee', '윤서해', 34, '수원시', 'e@e.com');
INSERT INTO MEMBER VALUES ('sss', 'sss', '김동준', 29, '광명시', 's@s.com');

SELECT * FROM MEMBER WHERE ID = 'aaa' AND PASSWD = 'aaa';