CREATE OR REPLACE PROCEDURE RES(VDEPTNO DEPT.DEPTNO%TYPE, VDNAME DEPT.DNAME%TYPE, VLOD DEPT.LOC%TYPE)
IS
V_SQL VARCHAR2(1000);
V_DEPTNO DEPT.DEPTNO%TYPE := VDEPTNO;
V_DNAME DEPT.DNAME%TYPE := VDNAME;
V_LOD DEPT.LOC%TYPE := VLOD;
BEGIN
--V_SQL := 'INSERT INTO DEPT01 VALUES ' || '(50, ''테스트'', ''서울'')';
V_SQL := 'INSERT INTO DEPT01 VALUES ' || '(:A, :A, :A)';
--EXECUTE IMMEDIATE V_SQL;
EXECUTE IMMEDIATE V_SQL USING V_DEPTNO, V_DNAME, V_LOD;
END;
/
-------------------------------------------------------------------------

CREATE SEQUENCE SUBJECT_SEQ NOCACHE;

CREATE SEQUENCE STUDENT_SEQ START WITH 202103020001 NOCACHE;

CREATE TABLE SUBJECT(
SNO NUMBER(4) PRIMARY KEY,
SNM VARCHAR2(20) NOT NULL);

CREATE TABLE STUDENT (
CNO NUMBER PRIMARY KEY,
NM VARCHAR2(10) NOT NULL,
TEL VARCHAR2(11) NOT NULL,
SNO NUMBER(4) REFERENCES SUBJECT(SNO));

INSERT INTO SUBJECT VALUES (SUBJECT_SEQ.NEXTVAL, '국어');
INSERT INTO SUBJECT VALUES (SUBJECT_SEQ.NEXTVAL, '영어');
INSERT INTO SUBJECT VALUES (SUBJECT_SEQ.NEXTVAL, '수학');
INSERT INTO SUBJECT VALUES (SUBJECT_SEQ.NEXTVAL, '사회');
INSERT INTO SUBJECT VALUES (SUBJECT_SEQ.NEXTVAL, '과학');
COMMIT;

INSERT INTO STUDENT VALUES (STUDENT_SEQ.NEXTVAL, '홍길동', '01000000000', 1);
INSERT INTO STUDENT VALUES (STUDENT_SEQ.NEXTVAL, '윤동주', '01000000000', 1);
INSERT INTO STUDENT VALUES (STUDENT_SEQ.NEXTVAL, '김소월', '01000000000', 2);
INSERT INTO STUDENT VALUES (STUDENT_SEQ.NEXTVAL, '안중근', '01000000000', 2);
INSERT INTO STUDENT VALUES (STUDENT_SEQ.NEXTVAL, '윤봉길', '01000000000', 3);
COMMIT;
-------------------------------------------------------------------------

CREATE TABLE N_MEMBER (
N_ID VARCHAR2(20) PRIMARY KEY,
N_PASSWD VARCHAR2(16) NOT NULL,
N_SUBEMAIL VARCHAR2(100),
N_NAME VARCHAR2(40) NOT NULL,
N_AGE VARCHAR2(8) NOT NULL,
N_GD VARCHAR2(6) NOT NULL,
N_NAT VARCHAR2(9) NOT NULL,
N_HPCP VARCHAR2(13) NOT NULL,
N_HP VARCHAR2(16) NOT NULL,
CONSTRAINT CK_GD CHECK (N_GD IN('남자', '여자')),
CONSTRAINT CK_NAT CHECK (N_NAT IN('내국인', '외국인')),
CONSTRAINT CK_HPCP CHECK (N_HPCP IN('SKT', 'KT', 'LGU+', 'SKT알뜰폰', 'KT알뜰폰', 'LGU+알뜰폰'))
);